- app/templates/auth/create-user.html
- app/templates/auth/request-password-reset.html
1. Added aria-describedby attribute on input fields where there is hint text.
2. Fixed missed page style formatting.
> Accessibility and missed page formatting

- circle.yml
I'll fix the tests in a separate PR
> add all ci config to circle.yml

- app/api_client/base.py
- app/api_client/data.py
- app/main/forms/auth_forms.py
- app/main/views/search.py
- application.py
- context_processors.py
- tests/app/views/test_buyers.py
- tests/app/views/test_errors.py
- tests/app/views/test_marketplace.py
- tests/app/views/test_services.py
This will give us a passing build
> fix pep8 errors

- app/main/views/marketplace.py
- app/templates/_base_landingpage_with_hero.html
- app/templates/_base_page_with_aside.html
- app/templates/about.html
- app/templates/content/contentpage-with-hero.html
- app/templates/content/contentpage.html
- app/templates/getting_started.html
1. Add new base page template with hero landing.
2. Add new base page template with aside/sidebar.
3. Add new About page.
> Page layout

- app/assets/scss/_buttons.scss
- app/assets/scss/_lists.scss
- app/assets/scss/_page-header.scss
- app/assets/scss/gov-au-ui-kit/_accordions.scss
- app/assets/scss/gov-au-ui-kit/_block-elements.scss
- app/assets/scss/gov-au-ui-kit/_buttons.scss
- app/assets/scss/gov-au-ui-kit/_colours.scss
- app/assets/scss/gov-au-ui-kit/_forms.scss
- app/assets/scss/gov-au-ui-kit/_grid-settings.scss
- app/assets/scss/gov-au-ui-kit/_icons.scss
- app/assets/scss/gov-au-ui-kit/_ie.scss
- app/assets/scss/gov-au-ui-kit/_images.scss
- app/assets/scss/gov-au-ui-kit/_lists.scss
- app/assets/scss/gov-au-ui-kit/_navigation.scss
- app/assets/scss/gov-au-ui-kit/_page-footer.scss
- app/assets/scss/gov-au-ui-kit/_page-header.scss
- app/assets/scss/gov-au-ui-kit/_print.scss
- app/assets/scss/gov-au-ui-kit/_tables.scss
- app/assets/scss/gov-au-ui-kit/_typography.scss
- app/assets/scss/gov-au-ui-kit/_variables.scss
- app/assets/scss/gov-au-ui-kit/_video.scss
- app/assets/scss/gov-au-ui-kit/ui-kit-icons.scss
- app/assets/scss/gov-au-ui-kit/ui-kit.scss
- app/assets/scss/ui-kit-icons.scss
- app/templates/main_template.html
- Add core scss files to their own folder
- Create and import all custom files by default
- Remove links to their compiled latest css and js files
> Add gov.au UI Kit core files and remove links to its latest

- requirements_for_test.txt
- tests/app/views/test_login.py
lxml 3.5 adds `.classes` attribute to HTML Element instances
> Fix test_login tests

- tests/app/views/test_marketplace.py
There's no EU cookie law or G-Cloud sidebar links so some tests can be removed.
> Remove homepage sidebar links and cookie notice tests

- app/assets/scss/_typography.scss
> Minor style tweaks for supplier details template.

- app/helpers/login_helpers.py
- app/main/views/login.py
- config.py
- requirements.txt
- tests/app/views/test_login.py
> SES emails

- app/assets/images/icons/chevron-up--white.svg
- app/assets/javascripts/_main.js
- app/assets/javascripts/application.js
- app/assets/scss/_colours.scss
- app/assets/scss/_icons.scss
- app/assets/scss/_navigation.scss
- app/assets/scss/_timelines.scss
- app/assets/scss/_typography.scss
- app/assets/scss/application.scss
- app/templates/_phase_banner.html
- app/templates/auth/create-buyer-user-error.html
- app/templates/buyers/studios_start_page.html
- app/templates/content/about-us.html
- app/templates/content/buyers-guide.html
- app/templates/content/contact-us.html
- app/templates/content/framework-digital-services.html
- app/templates/content/ideation.html
- app/templates/content/new-seller.html
- app/templates/content/pitch.html
- app/templates/content/roles-and-services.html
- app/templates/emails/create_buyer_user_email.html
- app/templates/emails/reset_password_email.html
- app/templates/errors/404.html
- app/templates/errors/410.html
- app/templates/main_template.html
- Add updates for content pages
- Add "back to top" functionality.
> Content pages

- app/main/forms/auth_forms.py
- tests/app/views/test_login.py
Some suggestions were made by the security team.
> Improve email address validation

- app/templates/_analytics.html
- config.py
I haven't added the production GA code to the config.
> Make the Google Analytics code configurable

- app/main/views/search.py
- app/templates/search_suppliers.html
fixed links in pagination and roles tag cloud
> Pagination fix

- app/main/views/search.py
there are approved suppliers with no suburb or state
tested with live api
> handle blank suburb and state

- app/assets/scss/_block-elements.scss
- app/assets/scss/_forms.scss
- app/assets/scss/_tables.scss
- app/assets/scss/_typography.scss
- app/templates/au-ui-toolkit/secondary-action-link.html
- app/templates/auth/create-buyer-account.html
- app/templates/auth/create-buyer-user-error.html
- app/templates/auth/login.html
- app/templates/auth/request-password-reset.html
- app/templates/content/about-us.html
- app/templates/content/buyers-guide.html
- app/templates/content/contact-us.html
- app/templates/content/ideation.html
- app/templates/content/new-seller.html
- app/templates/content/pitch.html
- app/templates/content/roles-and-services.html
- app/templates/suppliers_details.html
Content updates and style tweaks.
> Content and style tweaks.

- .cfignore
> dont deploy node files

- app/assets/scss/_pagination.scss
- app/assets/scss/application.scss
- app/templates/search_suppliers.html
Styled pagination on catalogue page.
> Pagination on catalogue page.

- app/assets/scss/_buttons.scss
- app/assets/scss/_lists.scss
- app/assets/scss/_pagination.scss
- app/templates/search_suppliers.html
- Minor bug fixes for some style issues
- Add back link to pagination controls for catalogue page
> Tweak to styles and add back link in pagination for catalogue page.

- app/__init__.py
- app/buyers/__init__.py
- app/helpers/login_helpers.py
- app/main/views/login.py
- config.py
- tests/app/views/test_login.py
Some of this could be moved into the utils repo.
> Set Cache-Control headers

- app/static/media/ie8/application-ie8-1.css
- app/static/media/ie8/application-ie8-2.css
- app/templates/_stylesheets.html
- application-ie8.css
- circle.yml
- gulpfile.js
- package.json
Testing split CSS files for IE8.
> Test IE8 fix

- config.py
We need some headers like "Cache-Control: must-revalidate", among other
things.
> Shorten cache time until some caching issues are fixed

- app/assets/scss/_search.scss
- app/assets/scss/application.scss
- app/templates/search_suppliers.html
- app/templates/sidebar/_filter_capabilities.html
- app/templates/sidebar/_search.html
Marketplace search box and filter area style updates
- new template file for search bar
- _search.scss added
- style updated
> Market sidebar search styles

- app/static/media/ie8/application-ie8-2.css
- application-ie8.css
> IE style updates.

- app/templates/content/buyers-guide.html
- app/templates/main_template.html
- JS file reference fix
- content updates
> JS file reference fix and content updates.

- app/templates/content/about-us.html
- app/templates/content/privacy-policy.html
- app/templates/index.html
- app/templates/main_template.html
- flexbox fix
- content updates
> Content updates and flexbox fix.

- app/assets/scss/application-ie8.scss
- app/static/media/ie8/application-ie8-2.css
- app/templates/main_template.html
- application-ie8.css
> Flex box fix

- app/__init__.py
This should help the interaction between caching and logins.
> Add Cookie to Vary header

- app/assets/scss/application-ie8.scss
- app/static/media/ie8/application-ie8-2.css
- app/templates/_footer_top.html
- app/templates/_javascripts.html
- app/templates/index.html
- app/templates/main_template.html
- application-ie8.css
> Shifting JS calls for flexibility to bottom of page.

- app/assets/scss/_search.scss
- app/templates/sidebar/_search.html
> Supplier page style updates

- app/assets/scss/_search.scss
> sidebar search style updates

- app/helpers/login_helpers.py
This was just for upgrading across the Flask Login API breaking change.
> Removed is_authenticated_workaround

- app/assets/scss/_colours.scss
- app/assets/scss/_typography.scss
- app/templates/search_suppliers.html
- Remove hero on catalogue page
- Change beta badge colours from purple/white to white/aqua
> Style tweaks

- circle.yml
- manifest.production.yml
zero downtime for marketplace buyer frontend
was uncertain what to do with DOCKER env vars so left them where they were
> blue-green-deploy

- app/templates/_footer.html
More clarification is needed about what is covered by this statement
> Remove copyright/license notice notice from footer

- circle.yml
this is the real hostname for prod - I have already modified routes in cf
> final prod route

- app/__init__.py
- app/helpers/__init__.py
- app/main/views/login.py
- requirements.txt
This is a part of our auditing requirements.
> Add logging of user actions

- app/main/forms/auth_forms.py
- app/main/views/login.py
- app/templates/auth/buyer-invite-request-complete.html
- app/templates/auth/buyer-invite-request.html
- app/templates/emails/buyer_account_invite_request_email.html
- config.py
- tests/app/views/test_login.py
A lot of changes are expected, but this gives the content editors, etc,
something to look at.
> Add frontend-visible stuff for the new moderated account creation system

- app/assets/scss/_buyerpages.scss
- app/templates/buyers/brief_publish_confirmation.html
Buyer Brief styes
- table font size
- table caption
- review and publish page styles
> Buyer brief styles

- circle.yml
We only need monitoring on prod build
> only do docker build on release

- app/assets/scss/_block-elements.scss
- app/assets/scss/_typography.scss
- app/main/views/marketplace.py
- app/templates/_footer_top.html
- app/templates/content/copyright.html
- app/templates/search_suppliers.html
- Add copyright page.
- Tweak catalogue page intro block.
> Add copyright page and tweak intro block of catalogue page.

- Makefile
- gulpfile.js
- package.json
Add livereload functionality to new FED build process.
> FED livereload

- app/buyers/views/buyers.py
- tests/app/views/test_buyers.py
This API change was made in the UK API client and was pulled in with a
merge.
> Replace update_brief_status with publish_brief

- app/main/forms/brief_forms.py
- app/main/views/marketplace.py
- tests/app/views/test_marketplace.py
Worryingly, this was committed about five days ago, but the build only
started failing today after an unrelated commit.
> Fix a broken import

- app/assets/scss/_block-elements.scss
- app/assets/scss/_buttons.scss
- app/assets/scss/_buyerpages.scss
- app/templates/buyers/brief_overview.html
- app/templates/buyers/brief_publish_confirmation.html
- app/templates/buyers/brief_responses.html
- app/templates/buyers/create_brief_question.html
- app/templates/buyers/dashboard.html
- app/templates/buyers/edit_brief_question.html
- app/templates/buyers/section_summary.html
- app/templates/buyers/start_brief_info.html
- tests/app/views/test_buyers.py
- Grid styles
- Callout info button styles
- Checkboxes
- Brief builder breadcrumbs.
> Brief builder styling

- app/assets/scss/_buyerpages.scss
- app/assets/scss/_forms.scss
- app/assets/scss/_typography.scss
- app/templates/brief.html
- Add style tweaks for optional label
- Fix for units labels
- Fix for validation messages
- Add style for information messages
- Add class to brief preview page template
> Grid updates

- app/main/views/login.py
- requirements.txt
Unused python libraries from requirements.txt removed.
There are at least three copies of the "hash_email" function in the
codebase.  Taking us one step closer to making that one.
> Small cleanup

- app/assets/scss/_block-elements.scss
- app/assets/scss/_buyerpages.scss
- app/assets/scss/_forms.scss
- app/assets/scss/_tables.scss
- app/templates/buyers/brief_overview.html
- bower.json
Style tweaks for brief builder.
> Brief Builder Style Updates

- config.py
We can increase this further when the site has stabilised more.
> Increase HTTP cache time in production to a day

- app/assets/scss/_buyerpages.scss
- app/assets/scss/_forms.scss
- app/templates/buyers/create_brief_question.html
- app/templates/buyers/edit_brief_question.html
- bower.json
- tests/app/views/test_buyers.py
Final tweaks to brief builder following minor fix to backend.
> Style fixes

- app/assets/scss/_buyerpages.scss
- app/assets/scss/_typography.scss
- bower.json
Fix validation message styling.
> Validation message styles

- app/assets/scss/_lists.scss
- app/assets/scss/_search.scss
- app/templates/search_suppliers.html
Tweak to Supplier Catalogue page.
> Supplier Catalogue

- app/templates/index.html
Re-ordering links on page and hiding links that aren't meant to be live.
> Tweak to homepage layout.

- app/templates/index.html
> Homepage tweaks

- app/assets/scss/_accordions.scss
- app/assets/scss/_lists.scss
- app/assets/scss/_search.scss
- app/templates/index.html
- app/templates/suppliers_details.html
General style tweaks to content and homepage.
> General style tweaks

- app/templates/search_suppliers.html
Changed some text on the seller catalogue page.
> Tweak to seller catalogue.

- monitoring/docker-compose-ecs.yml
- monitoring/docker-compose.yml
These are the servers we'll now be using in production.
> Update monitoring target

- monitoring/files/sensu-conf.d/marketplace.service.gov.au-https_checks.json
- monitoring/files/sensu-conf.d/marketplace.service.gov.au-pageload_checks.json
Main fix is replacing suppliers with sellers.
Updating alert names while I'm at it.
> Update monitoring configs

- config.py
> turn on brief builder

- app/assets/scss/_typography.scss
- app/templates/buyers/start_brief_info.html
- app/templates/guidance/answering_questions.html
- app/templates/index.html
- tests/app/views/test_digital_outcomes_and_specialists.py
- Updated content
- Heading style tweaks
> General tweaks

- app/templates/suppliers_details.html
Updated text references from "supplier" to "seller".
> Content fixes

- app/templates/content/copyright.html
- app/templates/content/disclaimer.html
- app/templates/content/privacy-policy.html
> Content sunday

- app/templates/index.html
- app/templates/main_template.html
Switch to "beta" from "private beta".
> Private Beta to Beta text change

- app/templates/main_template.html
Fix text to "BETA" instead of "PRIVATE BETA".
> Text update

- app/templates/index.html
> Tweak home page copy

- app/templates/index.html
> change text on home page

- app/assets/scss/_lists.scss
- Bug fix for vertical lists not using full width in IE10/11.
> CSS bug fix for IE10/11

- app/templates/content/capabilities-and-rates.html
- app/templates/guidance/answering_questions.html
- app/templates/guidance/evaluating_suppliers.html
- app/templates/guidance/shortlisting_suppliers.html
- tests/app/views/test_buyers.py
- Updates to the layout of content under the "guidance" folder
> Content updates

- app/main/views/marketplace.py
- app/templates/search/briefs.html
- config.py
Need to toggle this as it may to be styled before next release
> feature toggle the brief filters

- circle.yml
- scripts/cf_ha_deploy.sh
- service.gov.au-manifest.production.yml
- service.gov.au-manifest.staging.yml
> Remove legacy apps from Buyer frontend configs

- app/templates/auth/create-user.html
We now have one agreement document.
> Update copy for account creation

- app/assets/scss/_buyerpages.scss
- app/assets/scss/_lists.scss
- app/templates/_brief_q_and_a.html
- app/templates/auth/login.html
- app/templates/buyers/start_brief_info.html
- bower.json
- Updated bower.json with new front-end toolkit version.
- Tweaked some content.
- Updated some styles to fix some cross browser bugs.
> Cross browser bug fixes and content updates

- requirements.txt
This is to get the latest government email address domain whitelist.
> Upgrade utils

- app/templates/auth/buyer-invite-request.html
- app/templates/auth/buyer-signup.html
Removed reference to "privacy policy" which doesn't need to be accepted as part of user registration.
> Minor tweak to fine print on user registration screens

- app/assets/scss/_typography.scss
- app/assets/scss/application-print.scss
- app/templates/_stylesheets.html
Add new print stylesheet specifically for printing Brief summary
> New print stylesheet

- app/templates/search_sellers.html
- app/templates/sidebar/_filter_capabilities.html
Text changes to the seller catalogue page.
> Minor text content tweaks.

- app/templates/_footer_top.html
> Change to text in footer.

- app/templates/index.html
- Changed "capabilities" to "services"
- Switched order of links "individual" and "outcome"
> Text changes to homepage and re-ordering of homepage links.

- app/assets/scss/_typography.scss
- app/templates/search/briefs.html
Opportunities list brief badges tweaked with different colours for "Open to all"/"Open to selected" & "Open to one".
> Colour changes for badges on Opportunities list

- app/assets/scss/_lists.scss
- Remove list style tweaks for Safari IOS 8 (didn't work).
> Remove style tweaks

- app/templates/guidance/evaluating_suppliers.html
- Update content on 'How to evaluate sellers'.
> Copy update

- app/main/views/suppliers.py
- config.py
- tests/app/views/test_suppliers.py
- tests/helpers.py
This is protected by a feature flag.
> Allow supplier users to view their own supplier pages

- app/templates/_form_errors.html
- app/templates/auth/buyer-invite-request.html
- app/templates/auth/buyer-signup.html
- app/templates/auth/create-user.html
- app/templates/auth/login.html
- app/templates/auth/reset-password.html
This also makes sure they all have the ARIA attributes and have
consistent styling.
> Fold the form error box into a common template

- app/assets/scss/_links.scss
- app/assets/scss/_typography.scss
Update styles with new styles from Supplier Frontend.
> Style updates

- app/assets/scss/_block-elements.scss
- app/assets/scss/application-print.scss
- app/templates/brief.html
Add styling for "Download brief as PDF"
> Component styling

- app/templates/emails/mailout-base-template.html
Updated mailout email template.
> Mailout email template

- circle.yml
- scripts/ci-notify.sh
- tests/integration/config.py
- tests/integration/conftest.py
- tests/integration/features/catalogue.feature
- tests/integration/features/test_build_brief.py
- tests/integration/features/test_catalogue.py
- tests/integration/helpers.py
- run the tests on CI server after successful deployment to staging
- refactor fixtures/helpers
- cleanup test data (delete brief) after test execution
- remove failing scenario
> Refactor integration tests

- app/main/forms/auth_forms.py
- app/main/views/login.py
- app/templates/auth/accept-updated-terms.html
- config.py
- requirements.txt
- tests/app/views/test_login.py
- tests/helpers.py
This needs review by designers before going live.  Logic for blocking
site access for users with an outdated terms agreement will come later.
> Add a page for accepting updated terms of use

- app/main/views/suppliers.py
- config.py
This was behind a feature flag before.
> Allow suppliers to view their own pages

- app/assets/scss/_page-footer.scss
- app/templates/_footer_top.html
- app/templates/content/capabilities-and-rates.html
- app/templates/content/copyright.html
- app/templates/content/privacy-policy.html
Updated all external links with accessibility tweaks.
> Accessibility fixes

- app/assets/scss/_block-elements.scss
- app/assets/scss/_typography.scss
- app/templates/suppliers_details.html
Styled edit profile link on seller details page.
> Style edit profile link for seller profile

- tests/app/views/test_marketplace.py
I've added a test for the dashboard code on the homepage
> add a test for dashboard

- app/assets/scss/_block-elements.scss
- app/assets/scss/_buyerpages.scss
- app/templates/workorder/agency-details.html
- app/templates/workorder/select-seller.html
- app/templates/workorder/work-order-instruction-list.html
Add HTML template pages for work order flow.
> Work order flow

- app/assets/scss/_block-elements.scss
- app/assets/scss/_cards.scss
- app/assets/scss/_lists.scss
- app/assets/scss/application-print.scss
- app/assets/scss/application.scss
- app/templates/index.html
- app/templates/main_template.html
- tests/app/views/test_marketplace.py
> Homepage redesign

- app/assets/scss/_forms.scss
- app/assets/scss/_navigation.scss
- app/assets/scss/_page-header.scss
- app/assets/scss/_typography.scss
- app/templates/_footer_top.html
- app/templates/brief.html
- app/templates/buyers/brief_overview.html
- app/templates/buyers/dashboard.html
- app/templates/main_template.html
- app/templates/sidebar/_filter_capabilities.html
- app/templates/sidebar/_search.html
- bower.json
- tests/app/views/test_buyers.py
Fixes for accessibility issues.
> Accessibility tweaks

- app/buyers/views/buyers.py
- app/main/forms/work_order_forms.py
- app/templates/workorder/select-seller.html
- requirements.txt
- tests/app/views/test_buyers.py
This is the first page in the Work Order workflow.
A buyer will select a seller form the list of brief responses.
This page will eventually be linked from the buyer dashboard .
> Work order select seller

- app/templates/index.html
- config.py
- tests/integration/conftest.py
- tests/integration/features/home_page.feature
- tests/integration/features/home_page.py
- tests/integration/helpers.py
Edit: Do Not Merge yet
I also added some integration tests.
> Enable the dashboard on the home page

- app/main/forms/work_order_data.py
- app/main/forms/work_order_forms.py
- app/templates/macros/work_order_link.html
- app/templates/workorder/work-order-instruction-list.html
- mostly text and attribute name changes
- using an OrderedDict so we don't need a separate list of question slugs
> various work order copy changes

- app/buyers/views/work_orders.py
- app/templates/workorder/work-order-instruction-list.html
- tests/app/views/test_work_orders.py
Download a work order as a pdf
> Work order pdf

- .gitignore
- bower.json
- scripts/ci_build.sh
> Add timeframe question for outcomes lot

- app/templates/search_sellers.html
ie "Your search returned no results."
> Display a message when no results found in search

- monitoring/files/confd/templates/client.json.tmpl
- monitoring/files/sensu-conf.d/marketplace.service.gov.au-pageload_checks.json
As per instructions from cloud team:
https://techdocs.cfapps.io/platform/monitoring/sensu-client/
> add pagerduty config to sensu

- app/templates/content/sellers-guide.html
> Remove copy

- app/api_client/data.py
- app/assets/scss/_lists.scss
- app/helpers/react/render.py
- app/helpers/react/render_server.py
- app/helpers/shared_helpers.py
- app/main/views/suppliers.py
- app/templates/_react_component.html
- app/templates/suppliers_details.html
- config.py
- tests/app/views/test_case_studies.py
- tests/app/views/test_suppliers.py
- tests/fixtures/case_study_fixture.json
- tests/fixtures/supplier_fixture.json
- tests/fixtures/supplier_fixture_with_minium_data.json
- tests/fixtures/supplier_results.json
- tests/helpers.py
No editing/deleting and supplier view isn't entirely react-ified but good point to merge back.
> Basic case study listing and individual view

- app/main/forms/brief_forms.py
to account for launch of digital marketplace framework when multiple will be live
> Show opportunities/briefs from all frameworks

- .gitignore
- app/assets/images/icons/arrow-left.svg
- app/assets/scss/application.scss
- app/assets/svg/green-tick.svg
- app/templates/auth/login.html
- circle.yml
- gulpfile.js
- package.json
Config for uikit and some components added to package.json.
> Sample of uikit2 accessibility in login page

- app/buyers/views/buyers.py
- app/main/views/marketplace.py
- app/templates/brief.html
- app/templates/buyers/dashboard-briefs.html
- config.py
- tests/app/views/test_login.py
> Buyer dashboard teamview

- app/assets/scss/gov-au-ui-kit/_typography.scss
- app/templates/main_template.html
> Use system fonts like uikit2

- app/templates/index.html
AWS Product is above Google Analytics link
> aws product homepage location change

- app/templates/index.html
> [Home] Update panel and volume sourcing links

- app/main/views/suppliers.py
- tests/app/views/test_case_studies.py
This PR will restrict viewing case studies to users who are members of the supplier only, removing access for buyers.
> Lock down case studies
