.gitignore
tests/app/views/test_buyers.py
tests/app/views/test_errors.py
tests/app/views/test_login.py
tests/app/views/test_marketplace.py
tests/app/views/test_services.py

Disabled tests that are out of scope.
For now also disabled tests in login and marketplace - these are not being maintained.  Need to discuss with team what our approach with these will be.

disabling failing tests for now

---

app/templates/_base_page.html
app/templates/_footer_categories.html
app/templates/_phase_banner.html
app/templates/auth/create-buyer-user-error.html
app/templates/auth/login.html
app/templates/emails/reset_password_email.html

1. Correct HTML templates from .gov.uk to .gov.au
2. Correct email templates from .gov.uk to .gov.au

Fix .gov.uk references to .gov.au references.

---

app/main/views/suppliers.py
tests/app/views/test_suppliers.py

Viewing the supplier page requires a buyer login.
(Wait until it's possible to create users in dev before merging this)

Add login requirement for /suppliers/<code> page

---

app/main/views/search.py

This broke when the site was moved (issue #16)

Don't use a hardcoded URL for the search page

---

app/main/views/search.py

Categories are sorted alphabetically on the supplier page, this
adds the same sorting to the supplier info on the catalogue page.

Sort supplier categories on the supplier catalogue page

---

app/main/views/search.py

Protects the supplier catalogue page with a login before the launch

Add a temporary login requirement for the supplier catalogue

---

app/main/views/search.py

Catalogue login requirement was temporary, we don't want it on the live service.
This reverts commit 0b25f291b97b0dbdb0d2828bf68b7c63d49b02e8.
**NOTE** We don't want this to go to live just yet (but we need it to do a run-through on dev), so merging this early will probably block releases to live until we're close to the launch time.

Revert "Add a temporary login requirement for the supplier catalogue"

---

app/main/forms/auth_forms.py
app/main/views/login.py
app/templates/auth/buyer-invite-request.html
app/templates/auth/create-buyer-account.html
app/templates/auth/create-buyer-user-error.html
config.py
requirements.txt
tests/app/views/test_login.py

* Properly check email domains and give appropriate error messages
* Stop asking for terms acknowledgement on creation page (because admins
are using that now)

Fix up form validation for buyer account invite/creation

---

app/main/views/marketplace.py
app/templates/index.html
config.py

Put a link on the homepage but don't display on live
I am ignoring the flask feature-flags for now because I couldn't get them to work.
I don't think we need them anyway - we will want to change config value to put a feature live rather than rely on a date.

add brief builder link to homepage

---

app/templates/auth/create-buyer-account.html
app/templates/auth/create-buyer-user-error.html
app/templates/auth/login.html
app/templates/emails/buyer_account_invite_request_email.html
app/templates/main_template.html

We currently don't have a page for supplier account creation, so I
expect we'll create a new, general account creation landing page in the future.
That's why I haven't bothered updating the URLs to make this the
creation page.

Point account creation links to buyer account invite request page

---

README.md
lighttpd.conf
scripts/reverse_proxy.sh

The application is split into the buyer, supplier and admin frontends.
This simple reverse proxy can be run as a non-root user to put all the
apps behind one domain so that they integrate.
Currently only the supplier and buyer frontends are configured to work
behind this proxy.

Add a reverse proxy config for dev purposes

---

config.py

This way it can be overridden with environment variables.  I.e.,
export DM_SEND_EMAIL_TO_STDERR=True

Put DM_SEND_EMAIL_TO_STDERR in config

---

app/main/views/login.py
app/templates/auth/create-buyer-user-error.html
app/templates/auth/login.html
app/templates/index.html
app/templates/main_template.html
tests/app/views/test_login.py

The alternative process is being redesigned. Until that's done, buyer
account creation needs to be opened up again.

Re-enable the original buyer account creation process

---

app/buyers/views/buyers.py
tests/app/views/test_buyers.py

As the requirementLength was excluded from the unanswered_required, frontend did not know about the missing required field and allowed to be published. But the API raised validation error as the required field wasn't filled. Here is the snippet from the brief_publish_confirmation.html template.
```
{% if not published and unanswered_required > 0 %}
<div class="dmspeak">
<p><strong>You still need to complete the following questions before your requirements can be published:</strong></p>
</div>
{% for section in sections %}
{% for question in section.questions %}
{% if question.answer_required %}
<ul>
<li>
<a href="{{ url_for('.edit_brief_question', framework_slug=brief.frameworkSlug, lot_slug=brief.lotSlug, brief_id=brief.id, section_slug=section.slug, question_id=question.id) }}">{{ …
```

Publish brief

---

requirements_for_test.txt
setup.cfg
tests/integration/catalogue.feature
tests/integration/conftest.py
tests/integration/test_catalogue.py

Rather then inheriting all the ruby tests from the uk, most of which are broken and need to be re-written, I thought it was an opportunity to take a fresh approach with a Python-based bdd framework.  After assessing a few, https://github.com/pytest-dev/pytest-bdd looks the most promising:
- built off py.test which we are all familiar with
- makes use of py.test fixtures
- integrates well with our unit tests
- integrates with splinter project via https://github.com/pytest-dev/pytest-splinter
For now I've disabled the ./tests/integration folder in py.test config.  Need to figure out best way to run these tests in relation to release cycle.

Init bdd integration tests

---

app/__init__.py
app/helpers/login_helpers.py
config.py
requirements.txt
tests/app/views/test_buyers.py

CSS and other static files are being served from /marketplace.  This is
because the CSS is built once in CI, so it isn't simple to have
different paths.  The CSS contains references to icons.

Allow the site to serve from / instead of /marketplace

---

app/__init__.py
app/main/views/search.py
config.py
requirements.txt

This means we don't hit the database on every page render, which
increases our capacity to serve this page multiple times.

Cache the roles on the search page

---

circle.yml

I confirmed with Michael that the Sensu stuff does not need to be run on every live deploy - only when the monitoring config changes
This is a bit of a kludge but will at least speed up the live builds.

separate the monitoring build steps

---

app/main/views/marketplace.py
app/templates/brief.html
config.py
requirements.txt
tests/app/views/test_marketplace.py

Found https://pythonhosted.org/Flask-WeasyPrint that does not make network call for relative urls.
Featured-flagged the link for now.

add pdf download to brief page

---

circle.yml
scripts/ci-notify.sh

Simple script that sends notification for live builds only
Couldn't find anything out-of-the-box that just did notifications on github release eg. the github slack app sends notifications for tags + branches which would be too noisy

send slack notification on prod build

---

app/templates/auth/buyer-invite-request.html
app/templates/auth/buyer-signup.html

The government email address domain whitelist is no longer restricted to
.gov.au

Tweak copy for buyer account registration

---

app/templates/suppliers_details.html

Hide endorsements and case studies of seller details - not being used yet.

Hide non-used sections of seller details

---

app/main/views/marketplace.py

This isn't being used by frontend devs.

Remove raw template render feature

---

app/assets/scss/_tables.scss
bower.json

Adding `pre-wrap` to the textarea fields. pre-wrap preserves new lines, spaces and tabs while wrapping text.

Add corresponding CSS to preserve whitespace in templates

---

circle.yml
requirements.txt
scripts/cf_deploy_all.sh
scripts/cf_ha_deploy.sh

The cffi library seems to be needed for new pushes to work properly.
Pushes to existing apps seem to have worked because the containers
already had the library installed from earlier versions of the
application.

Stop staging downtime on push

---

app/main/views/login.py

The session flag doesn't seem to be cleared by the logout.

Fix redirect loop when logging out from terms update page

---

app/main/views/marketplace.py
tests/app/views/test_marketplace.py

Dependent on https://github.com/AusDTO/dto-digitalmarketplace-api/pull/64
Briefs were being split (and recombined in the frontend) based on who they are open to. This is not required and could omit some that were made before this data was added.

Use explicit total briefs count on homepage dashboard

---

config.py

We can't remove the feature flag completely until it's removed from
utils.

Make the new update terms review feature live

---

app/main/forms/brief_forms.py
tests/app/views/test_marketplace.py

This ensures the sorting is open by published date then closed by published date so the first page has all the open opportunities (Brief.query.order_by(Brief.status.desc(), Brief.published_at.desc()))

Use 'human' sort for opportunities listing

---

app/main/views/marketplace.py

The frontpage dashboard now takes just one API request. Also proxy /metrics back to the API.

Use more efficent metrics API and proxy JSON format

---

app/templates/content/terms-of-use/2017-02-22 12:00.html

This PR: fixes the Indemnity table of contents link in the Terms of Use page, by correcting a typo in the indemnity section.

Fix anchor id typo.

---

app/main/views/marketplace.py
app/templates/_footer.html
tests/app/views/test_marketplace.py

This pull request updates footer links so they point to the new Zendesk pages.  It also adds redirects for the old routes.
Addresses MAR-3320

[Footer] Update terms of use, privacy, security, disclaimer and copyright links

---

requirements.txt

I ran into a problem where I couldn't upload files locally when testing the application flow. I discovered that the utils repository was running later versions of the boto packages. This pull request updates the boto packages to make them consistent with what utils is running.

Bump boto package versions to match what utils is using

---

app/main/views/search.py

`AttributeError: 'NoneType' object has no attribute 'keys'` is triggered when searching for sellers in the seller catalogue and a seller is returned without `seller_type`.  This pull request fixes this by checking for `seller_type` before the call to the `keys` function.
Addresses MAR-4286

Check seller_type before calling the keys function
